title: The 5th AGILEHAND Plenary Meeting
page-top-title: December 2-6, 2024
top-section-bg-text: AGILEHAND
home-subtitle: Tokyo University of Technology
copyright-text: 'The 5th AGILEHAND Plenary Meeting. All Rights Reserved.'
